### ISSUE TITLE
save the coordinated bounding box

### ISSUE THREAD

**Issue by qillbel** [vincentgong7/VG_AlexeyAB_darknet#11]
Hi there,

Could you help me modify the codes to write the coordinate bounding boxes next to the percentage in the result.txt

I've tried to modify image.c as suggested with no luck. Thank you so much for your help/

**Comment by vincentgong7** [comment]
Hi, this feature is implemented in our updated version yesterday. Please check it out. If possible, please let me know how it works in your environment.
