### ISSUE TITLE
Format of .json file and .txt file generated

### ISSUE THREAD

**Issue by deeplearner93** [vincentgong7/VG_AlexeyAB_darknet#18]
Hello @vincentgong7 

The json file and .txt file gets generated  without any Trouble.

I have 2 queries.
 1. What Format of .json file is followed? i.e. I think we have different dataset Annotation Format. 
For example, I would like to convert the generated text file and .json file into COCO Format/VOC Format or in yolo Format.

2. Is there a way to generate separate text and .json files for each Image ?. Right now we have one Output file that contains all Information about all the Image file and all objects.

Thank you in Advance.!

**Comment by vincentgong7** [comment]
Hi,

For your questions:
1. I did not follow any specific format. Either I can adapt to those format
in the next commit, or you can transfer the current format to your ideal
format with writing a transfer format programme.
2. For sure, that is easy to generate separate files. Same here, either I
add this into next version, or you can write a programme to do that. It's
easy.



Regards,

Vincent X. Gong

**Comment by deeplearner93** [comment]
Thank you
