### ISSUE TITLE
Gtk-WARNING **: cannot open display: 

### ISSUE THREAD

**Issue by yustiks** [vincentgong7/VG_AlexeyAB_darknet#2]
Hello! I am trying to run your program, but I have this error:
"mask_scale: Using default '1.000000'
Loading weights from weights/yolo-voc.backup...Done!

(145:15882): Gtk-WARNING **: cannot open display: "

Basically, the program predicts one image and saves the results, but after 1 image it stops with this phrase. What is your suggestion?
**UPDATE**
I figured out it was a problem with opencv library, so I had to make opencv=0 in Makefile and run command make again, so it worked for me

**Comment by vincentgong7** [comment]
Hi Yustiks,

Nice to know that you solved it. Yes, if you do not use OpenCV, set it as 0. Great! Enjoy using it. Hope it help u anyway. 

BR,
Vincent

**Comment by Vic-TheGreat** [comment]
Quick question, why is it unable to combine with openCV?? ...... I would like to know for the knowledge.
Thanks!

cheers!!

**Comment by vincentgong7** [comment]
It should be able to combine with the openCV. Maybe some problems in configuration.

**Comment by vincentgong7** [comment]
Could you try the original version and test if the same problem occurs?

**Comment by Vic-TheGreat** [comment]
Oh maybe that's the problem.... is there a specif way to open with openCV? ..... I simply run with the command 
`./darknet detector batch cfg/coco.data cfg/yolov3.cfg weights/yolov3.weights batch exp/in_images/ exp/out_images/ > exp/results/results.txt`

**Comment by vincentgong7** [comment]
In the Makefile in the root folder of this project, you could specify if you use Opencv or not:
OPENCV=0
or:
OPENCV=1

Once the Makefile is modified, you should compile this project again. For example, on Linux, the command is "make".
After that, you can use the command you mentioned to bach process images.

**Comment by DoSquared** [comment]
I have this issue and I cannot fix it after changing open CV
