### ISSUE TITLE
No error but objects in output images are not detected. Weight does not work.

### ISSUE THREAD

**Issue by Vic-TheGreat** [vincentgong7/VG_AlexeyAB_darknet#3]
I have tried all the weights available on the official YOLO websites, however, none actually detects objects in the output file except  [https://pjreddie.com/media/files/yolov3.weights](url)

Does anyone know why?
This is also evident in the output text file.
This is the result gotten when the weight YOLOv3 open Image weight is used
![with yolov3 openImage weight](https://user-images.githubusercontent.com/43807311/58256745-d3d05b00-7d6f-11e9-89f5-dd6dbd8452a8.png)

This is the result gotten when YOLOv3 weight is used.
![with yolov3 weights](https://user-images.githubusercontent.com/43807311/58256862-0bd79e00-7d70-11e9-9319-aebdc9e2f503.png)

I would like to know. Thanks.

**Comment by vincentgong7** [comment]
did you try this: https://pjreddie.com/media/files/yolov3-openimages.weights
